# Artillery Load Testing Configuration for Career Advisor Backend
# Run with: npx artillery run artillery-config.yml

config:
  target: "http://localhost:5000"
  phases:
    # Warm-up phase
    - duration: 60
      arrivalRate: 5
      name: "Warm-up (5 users/sec)"

    # Ramp up phase
    - duration: 120
      arrivalRate: 10
      rampTo: 50
      name: "Ramp-up (10 to 50 users/sec)"

    # Sustained load
    - duration: 300
      arrivalRate: 50
      name: "Sustained load (50 users/sec)"

    # Peak load
    - duration: 60
      arrivalRate: 100
      name: "Peak load (100 users/sec)"

    # Cool down
    - duration: 60
      arrivalRate: 10
      name: "Cool-down (10 users/sec)"

  # Plugins
  plugins:
    metrics-by-endpoint: {}

  # Request defaults
  defaults:
    headers:
      Content-Type: "application/json"

  # Performance thresholds
  ensure:
    maxErrorRate: 1  # Max 1% error rate
    p95: 2000        # 95th percentile response time < 2 seconds
    p99: 5000        # 99th percentile response time < 5 seconds

scenarios:
  # Health Check Scenario
  - name: "Health Check"
    weight: 10
    flow:
      - get:
          url: "/api/health"
          expect:
            - statusCode: 200

  # Jobs API Scenario
  - name: "Job Search and Recommendations"
    weight: 30
    flow:
      # Search jobs
      - get:
          url: "/api/jobs/search?query=developer&location=remote"
          expect:
            - statusCode: 200
            - contentType: json

      # Get job recommendations (requires auth - mock for now)
      - get:
          url: "/api/jobs/recommendations"
          headers:
            Authorization: "Bearer test-token"

  # Scholarships API Scenario
  - name: "Scholarship Search"
    weight: 20
    flow:
      - get:
          url: "/api/scholarships"
          expect:
            - statusCode: 200

      - get:
          url: "/api/scholarships?category=undergraduate&location=USA"
          expect:
            - statusCode: 200

  # Internships API Scenario
  - name: "Internship Search"
    weight: 15
    flow:
      - get:
          url: "/api/internships"
          expect:
            - statusCode: 200

  # User Profile Scenario (requires authentication)
  - name: "User Profile Operations"
    weight: 15
    flow:
      # Note: This will likely fail without valid auth token
      # Update with real token for authenticated testing
      - post:
          url: "/api/user/profile"
          headers:
            Authorization: "Bearer test-token"
          json:
            skills: ["JavaScript", "React", "Node.js"]
            experience: "2 years"
            education: "Bachelor's in Computer Science"

  # Analytics Tracking
  - name: "Analytics Events"
    weight: 10
    flow:
      - post:
          url: "/api/analytics/track"
          json:
            event: "page_view"
            page: "/dashboard"
            timestamp: "{{ $timestamp }}"
